---
- name: check distro
  fail:
    msg: "distro {{ ansible_facts['distribution'] }} not supported"
  when: ansible_facts['distribution'] != 'Ubuntu' and ansible_os_family != 'RedHat'

- name: check that docker is installed
  command: which docker
  changed_when: false

- name: ubuntu pre-install tasks
  include_tasks: ubuntu-pre-install.yml
  when: ansible_distribution == 'Ubuntu'

- name: redhat family pre-install tasks
  include_tasks: redhat-pre-install.yml
  when: ansible_os_family == 'RedHat'

- name: set docker daemon configuration
  copy:
    content: "{{ docker_daemon_json | to_nice_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  register: daemon_json

- name: grab nvidia-docker wrapper
  get_url:
    url: "{{ nvidia_docker_wrapper_url }}"
    dest: /usr/local/bin/nvidia-docker
    mode: 0755
    owner: root
    group: root

- name: reload docker service
  service:
    name: docker
    state: reloaded
  when: install_packages.changed or daemon_json.changed
