---
- name: remove packages
  yum:
    name:
      - nvidia-docker
      - nvidia-docker2
    state: absent
    autoremove: yes

- name: add repo
  get_url:
    url: "{{ nvdocker_repo_base_url }}/{{ rhel_repo_dist_name }}/{{ rhel_repo_file_name }}"
    dest: "{{ rhel_repo_file_path }}"
    mode: 0644
    owner: root
    group: root

- name: install packages
  yum:
    name: nvidia-container-runtime
    state: present
    update_cache: yes
  register: install_packages
