---
- name: remove packages
  apt:
    name:
      - nvidia-docker
      - nvidia-docker2
    state: absent
    autoremove: yes
    purge: yes

- name: add key
  apt_key:
    url: "{{ nvdocker_gpg_path }}"
    state: present

- name: add repo
  get_url:
    url: "{{ nvdocker_repo_base_url }}/{{ ubuntu_repo_dist_name }}/{{ ubuntu_repo_file_name }}"
    dest: "{{ ubuntu_repo_file_path }}"
    mode: 0644
    owner: root
    group: root

- name: install packages
  apt:
    name: nvidia-container-runtime
    state: present
    update_cache: yes
  register: install_packages

